import type { DesignPreset, QuizDesign } from './types';

export const DEFAULT_DESIGN: QuizDesign = {
  presetId: 'aurora',
  primary: '#6366f1',
  background: '#0b0d17',
  surface: '#151827',
  text: '#f1f5f9',
  muted: '#94a3b8',
  radius: 16,
  fontHeading: 'Inter',
  fontBody: 'Inter',
  buttonStyle: 'gradient',
  progressStyle: 'bar',
};

export const DESIGN_PRESETS: DesignPreset[] = [
  {
    id: 'aurora',
    name: 'Aurora',
    description: 'Dark premium com gradiente violeta',
    design: { ...DEFAULT_DESIGN, presetId: 'aurora' },
  },
  {
    id: 'minimal-light',
    name: 'Minimal Light',
    description: 'Clean, tipografia forte',
    design: {
      presetId: 'minimal-light',
      primary: '#111827',
      background: '#ffffff',
      surface: '#f8fafc',
      text: '#0f172a',
      muted: '#64748b',
      radius: 8,
      fontHeading: 'Inter',
      fontBody: 'Inter',
      buttonStyle: 'solid',
      progressStyle: 'steps',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Coral vibrante, warm',
    design: {
      presetId: 'sunset',
      primary: '#f97316',
      background: '#1a0f0a',
      surface: '#26140c',
      text: '#fff7ed',
      muted: '#fdba74',
      radius: 20,
      fontHeading: 'Inter',
      fontBody: 'Inter',
      buttonStyle: 'gradient',
      progressStyle: 'bar',
    },
  },
  {
    id: 'emerald',
    name: 'Emerald',
    description: 'Verde institucional, confiança',
    design: {
      presetId: 'emerald',
      primary: '#10b981',
      background: '#052e2b',
      surface: '#083f3a',
      text: '#ecfdf5',
      muted: '#6ee7b7',
      radius: 14,
      fontHeading: 'Inter',
      fontBody: 'Inter',
      buttonStyle: 'solid',
      progressStyle: 'bar',
    },
  },
  {
    id: 'rose',
    name: 'Rose Luxe',
    description: 'Estética, beleza, alto ticket',
    design: {
      presetId: 'rose',
      primary: '#e11d48',
      background: '#1a0812',
      surface: '#2a0f1c',
      text: '#fff1f2',
      muted: '#fda4af',
      radius: 24,
      fontHeading: 'Inter',
      fontBody: 'Inter',
      buttonStyle: 'gradient',
      progressStyle: 'dots',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Azul profundo, corporativo',
    design: {
      presetId: 'ocean',
      primary: '#0ea5e9',
      background: '#031425',
      surface: '#062038',
      text: '#e0f2fe',
      muted: '#7dd3fc',
      radius: 12,
      fontHeading: 'Inter',
      fontBody: 'Inter',
      buttonStyle: 'solid',
      progressStyle: 'bar',
    },
  },
  {
    id: 'mono',
    name: 'Mono',
    description: 'Preto e branco, editorial',
    design: {
      presetId: 'mono',
      primary: '#000000',
      background: '#ffffff',
      surface: '#f4f4f5',
      text: '#0a0a0a',
      muted: '#71717a',
      radius: 4,
      fontHeading: 'Inter',
      fontBody: 'Inter',
      buttonStyle: 'solid',
      progressStyle: 'steps',
    },
  },
  {
    id: 'gold',
    name: 'Gold',
    description: 'Luxo, alto padrão',
    design: {
      presetId: 'gold',
      primary: '#d4a24c',
      background: '#0a0a0a',
      surface: '#151312',
      text: '#faf5eb',
      muted: '#a89272',
      radius: 10,
      fontHeading: 'Inter',
      fontBody: 'Inter',
      buttonStyle: 'outline',
      progressStyle: 'bar',
    },
  },
  {
    id: 'candy',
    name: 'Candy',
    description: 'Divertido, jovem, vibrante',
    design: {
      presetId: 'candy',
      primary: '#a855f7',
      background: '#faf5ff',
      surface: '#ffffff',
      text: '#3b0764',
      muted: '#a78bfa',
      radius: 28,
      fontHeading: 'Inter',
      fontBody: 'Inter',
      buttonStyle: 'gradient',
      progressStyle: 'dots',
    },
  },
];
