/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as GoogleOauthCallbackRouteImport } from './routes/google-oauth-callback'
import { Route as MetaOauthCallbackRouteImport } from './routes/meta-oauth-callback'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAutomationsRouteImport } from './routes/_app.automations'
import { Route as AppChatReportsRouteImport } from './routes/_app.chat-reports'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFormsRouteImport } from './routes/_app.forms'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppObservabilityRouteImport } from './routes/_app.observability'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppQuizzesRouteImport } from './routes/_app.quizzes'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as ChatEmbedCompanyIdRouteImport } from './routes/chat-embed.$companyId'
import { Route as EmbedFormIdRouteImport } from './routes/embed-form.$id'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as QSlugRouteImport } from './routes/q.$slug'
import { Route as AppAnalyticsTvRouteImport } from './routes/_app.analytics.tv'
import { Route as AppIntegrationsMetaRouteImport } from './routes/_app.integrations.meta'
import { Route as AppLeadsIdRouteImport } from './routes/_app.leads.$id'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsAutomationsRouteImport } from './routes/_app.settings.automations'
import { Route as AppSettingsChatRouteImport } from './routes/_app.settings.chat'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app.settings.company'
import { Route as AppSettingsInstallRouteImport } from './routes/_app.settings.install'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app.settings.integrations'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsQuickRepliesRouteImport } from './routes/_app.settings.quick-replies'
import { Route as AppSettingsRoutingRouteImport } from './routes/_app.settings.routing'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app.settings.security'
import { Route as AppSettingsWidgetsRouteImport } from './routes/_app.settings.widgets'
import { Route as ApiPublicMetaWebhookRouteImport } from './routes/api/public/meta-webhook'
import { Route as ApiPublicPixelEventRouteImport } from './routes/api/public/pixel-event'
import { Route as ApiPublicWhatsappCapiRetryRouteImport } from './routes/api/public/whatsapp-capi-retry'
import { Route as ApiPublicWhatsappClickRouteImport } from './routes/api/public/whatsapp-click'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as FunctionsV1OauthCallbackRouteImport } from './routes/functions.v1.oauth-callback'
import { Route as IntegrationsMetaCallbackRouteImport } from './routes/integrations.meta.callback'
import { Route as AppQuizzesIdBuilderRouteImport } from './routes/_app.quizzes_.$id.builder'
import { Route as AppQuizzesIdFlowRouteImport } from './routes/_app.quizzes_.$id.flow'
import { Route as AppQuizzesIdLeadsRouteImport } from './routes/_app.quizzes_.$id.leads'
import { Route as AppQuizzesIdPerformanceRouteImport } from './routes/_app.quizzes_.$id.performance'
import { Route as AppQuizzesIdPreviewRouteImport } from './routes/_app.quizzes_.$id.preview'
import { Route as AppQuizzesIdPublishRouteImport } from './routes/_app.quizzes_.$id.publish'
import { Route as ApiPublicCronMetaRetryRouteImport } from './routes/api/public/cron/meta-retry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleOauthCallbackRoute = GoogleOauthCallbackRouteImport.update({
  id: '/google-oauth-callback',
  path: '/google-oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaOauthCallbackRoute = MetaOauthCallbackRouteImport.update({
  id: '/meta-oauth-callback',
  path: '/meta-oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppChatReportsRoute = AppChatReportsRouteImport.update({
  id: '/chat-reports',
  path: '/chat-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppObservabilityRoute = AppObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const ChatEmbedCompanyIdRoute = ChatEmbedCompanyIdRouteImport.update({
  id: '/chat-embed/$companyId',
  path: '/chat-embed/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedFormIdRoute = EmbedFormIdRouteImport.update({
  id: '/embed-form/$id',
  path: '/embed-form/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QSlugRoute = QSlugRouteImport.update({
  id: '/q/$slug',
  path: '/q/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsTvRoute = AppAnalyticsTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AppAnalyticsRoute,
} as any)
const AppIntegrationsMetaRoute = AppIntegrationsMetaRouteImport.update({
  id: '/integrations/meta',
  path: '/integrations/meta',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIdRoute = AppLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAutomationsRoute = AppSettingsAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsChatRoute = AppSettingsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsInstallRoute = AppSettingsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsQuickRepliesRoute = AppSettingsQuickRepliesRouteImport.update({
  id: '/quick-replies',
  path: '/quick-replies',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsRoutingRoute = AppSettingsRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsWidgetsRoute = AppSettingsWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiPublicMetaWebhookRoute = ApiPublicMetaWebhookRouteImport.update({
  id: '/api/public/meta-webhook',
  path: '/api/public/meta-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixelEventRoute = ApiPublicPixelEventRouteImport.update({
  id: '/api/public/pixel-event',
  path: '/api/public/pixel-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappCapiRetryRoute =
  ApiPublicWhatsappCapiRetryRouteImport.update({
    id: '/api/public/whatsapp-capi-retry',
    path: '/api/public/whatsapp-capi-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappClickRoute = ApiPublicWhatsappClickRouteImport.update({
  id: '/api/public/whatsapp-click',
  path: '/api/public/whatsapp-click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const FunctionsV1OauthCallbackRoute =
  FunctionsV1OauthCallbackRouteImport.update({
    id: '/functions/v1/oauth-callback',
    path: '/functions/v1/oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationsMetaCallbackRoute =
  IntegrationsMetaCallbackRouteImport.update({
    id: '/integrations/meta/callback',
    path: '/integrations/meta/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppQuizzesIdBuilderRoute = AppQuizzesIdBuilderRouteImport.update({
  id: '/quizzes_/$id/builder',
  path: '/quizzes/$id/builder',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIdFlowRoute = AppQuizzesIdFlowRouteImport.update({
  id: '/quizzes_/$id/flow',
  path: '/quizzes/$id/flow',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIdLeadsRoute = AppQuizzesIdLeadsRouteImport.update({
  id: '/quizzes_/$id/leads',
  path: '/quizzes/$id/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIdPerformanceRoute = AppQuizzesIdPerformanceRouteImport.update({
  id: '/quizzes_/$id/performance',
  path: '/quizzes/$id/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIdPreviewRoute = AppQuizzesIdPreviewRouteImport.update({
  id: '/quizzes_/$id/preview',
  path: '/quizzes/$id/preview',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIdPublishRoute = AppQuizzesIdPublishRouteImport.update({
  id: '/quizzes_/$id/publish',
  path: '/quizzes/$id/publish',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCronMetaRetryRoute = ApiPublicCronMetaRetryRouteImport.update({
  id: '/api/public/cron/meta-retry',
  path: '/api/public/cron/meta-retry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/google-oauth-callback': typeof GoogleOauthCallbackRoute
  '/meta-oauth-callback': typeof MetaOauthCallbackRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/analytics': typeof AppAnalyticsRouteWithChildren
  '/automations': typeof AppAutomationsRoute
  '/chat-reports': typeof AppChatReportsRoute
  '/dashboard': typeof AppDashboardRoute
  '/forms': typeof AppFormsRoute
  '/inbox': typeof AppInboxRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/observability': typeof AppObservabilityRoute
  '/pipeline': typeof AppPipelineRoute
  '/quizzes': typeof AppQuizzesRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/whatsapp': typeof AppWhatsappRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/chat-embed/$companyId': typeof ChatEmbedCompanyIdRoute
  '/embed-form/$id': typeof EmbedFormIdRoute
  '/f/$slug': typeof FSlugRoute
  '/q/$slug': typeof QSlugRoute
  '/analytics/tv': typeof AppAnalyticsTvRoute
  '/integrations/meta': typeof AppIntegrationsMetaRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/settings/automations': typeof AppSettingsAutomationsRoute
  '/settings/chat': typeof AppSettingsChatRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/install': typeof AppSettingsInstallRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/quick-replies': typeof AppSettingsQuickRepliesRoute
  '/settings/routing': typeof AppSettingsRoutingRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/widgets': typeof AppSettingsWidgetsRoute
  '/api/public/meta-webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/pixel-event': typeof ApiPublicPixelEventRoute
  '/api/public/whatsapp-capi-retry': typeof ApiPublicWhatsappCapiRetryRoute
  '/api/public/whatsapp-click': typeof ApiPublicWhatsappClickRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/functions/v1/oauth-callback': typeof FunctionsV1OauthCallbackRoute
  '/integrations/meta/callback': typeof IntegrationsMetaCallbackRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/quizzes/$id/builder': typeof AppQuizzesIdBuilderRoute
  '/quizzes/$id/flow': typeof AppQuizzesIdFlowRoute
  '/quizzes/$id/leads': typeof AppQuizzesIdLeadsRoute
  '/quizzes/$id/performance': typeof AppQuizzesIdPerformanceRoute
  '/quizzes/$id/preview': typeof AppQuizzesIdPreviewRoute
  '/quizzes/$id/publish': typeof AppQuizzesIdPublishRoute
  '/api/public/cron/meta-retry': typeof ApiPublicCronMetaRetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/google-oauth-callback': typeof GoogleOauthCallbackRoute
  '/meta-oauth-callback': typeof MetaOauthCallbackRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/analytics': typeof AppAnalyticsRouteWithChildren
  '/automations': typeof AppAutomationsRoute
  '/chat-reports': typeof AppChatReportsRoute
  '/dashboard': typeof AppDashboardRoute
  '/forms': typeof AppFormsRoute
  '/inbox': typeof AppInboxRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/observability': typeof AppObservabilityRoute
  '/pipeline': typeof AppPipelineRoute
  '/quizzes': typeof AppQuizzesRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/chat-embed/$companyId': typeof ChatEmbedCompanyIdRoute
  '/embed-form/$id': typeof EmbedFormIdRoute
  '/f/$slug': typeof FSlugRoute
  '/q/$slug': typeof QSlugRoute
  '/analytics/tv': typeof AppAnalyticsTvRoute
  '/integrations/meta': typeof AppIntegrationsMetaRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/settings/automations': typeof AppSettingsAutomationsRoute
  '/settings/chat': typeof AppSettingsChatRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/install': typeof AppSettingsInstallRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/quick-replies': typeof AppSettingsQuickRepliesRoute
  '/settings/routing': typeof AppSettingsRoutingRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/widgets': typeof AppSettingsWidgetsRoute
  '/api/public/meta-webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/pixel-event': typeof ApiPublicPixelEventRoute
  '/api/public/whatsapp-capi-retry': typeof ApiPublicWhatsappCapiRetryRoute
  '/api/public/whatsapp-click': typeof ApiPublicWhatsappClickRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/functions/v1/oauth-callback': typeof FunctionsV1OauthCallbackRoute
  '/integrations/meta/callback': typeof IntegrationsMetaCallbackRoute
  '/settings': typeof AppSettingsIndexRoute
  '/quizzes/$id/builder': typeof AppQuizzesIdBuilderRoute
  '/quizzes/$id/flow': typeof AppQuizzesIdFlowRoute
  '/quizzes/$id/leads': typeof AppQuizzesIdLeadsRoute
  '/quizzes/$id/performance': typeof AppQuizzesIdPerformanceRoute
  '/quizzes/$id/preview': typeof AppQuizzesIdPreviewRoute
  '/quizzes/$id/publish': typeof AppQuizzesIdPublishRoute
  '/api/public/cron/meta-retry': typeof ApiPublicCronMetaRetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/diagnostics': typeof DiagnosticsRoute
  '/google-oauth-callback': typeof GoogleOauthCallbackRoute
  '/meta-oauth-callback': typeof MetaOauthCallbackRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/_app/analytics': typeof AppAnalyticsRouteWithChildren
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/chat-reports': typeof AppChatReportsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/forms': typeof AppFormsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/observability': typeof AppObservabilityRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/quizzes': typeof AppQuizzesRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/chat-embed/$companyId': typeof ChatEmbedCompanyIdRoute
  '/embed-form/$id': typeof EmbedFormIdRoute
  '/f/$slug': typeof FSlugRoute
  '/q/$slug': typeof QSlugRoute
  '/_app/analytics/tv': typeof AppAnalyticsTvRoute
  '/_app/integrations/meta': typeof AppIntegrationsMetaRoute
  '/_app/leads/$id': typeof AppLeadsIdRoute
  '/_app/settings/automations': typeof AppSettingsAutomationsRoute
  '/_app/settings/chat': typeof AppSettingsChatRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
  '/_app/settings/install': typeof AppSettingsInstallRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/quick-replies': typeof AppSettingsQuickRepliesRoute
  '/_app/settings/routing': typeof AppSettingsRoutingRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/settings/widgets': typeof AppSettingsWidgetsRoute
  '/api/public/meta-webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/pixel-event': typeof ApiPublicPixelEventRoute
  '/api/public/whatsapp-capi-retry': typeof ApiPublicWhatsappCapiRetryRoute
  '/api/public/whatsapp-click': typeof ApiPublicWhatsappClickRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/functions/v1/oauth-callback': typeof FunctionsV1OauthCallbackRoute
  '/integrations/meta/callback': typeof IntegrationsMetaCallbackRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/quizzes_/$id/builder': typeof AppQuizzesIdBuilderRoute
  '/_app/quizzes_/$id/flow': typeof AppQuizzesIdFlowRoute
  '/_app/quizzes_/$id/leads': typeof AppQuizzesIdLeadsRoute
  '/_app/quizzes_/$id/performance': typeof AppQuizzesIdPerformanceRoute
  '/_app/quizzes_/$id/preview': typeof AppQuizzesIdPreviewRoute
  '/_app/quizzes_/$id/publish': typeof AppQuizzesIdPublishRoute
  '/api/public/cron/meta-retry': typeof ApiPublicCronMetaRetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/google-oauth-callback'
    | '/meta-oauth-callback'
    | '/oauth-callback'
    | '/analytics'
    | '/automations'
    | '/chat-reports'
    | '/dashboard'
    | '/forms'
    | '/inbox'
    | '/leads'
    | '/observability'
    | '/pipeline'
    | '/quizzes'
    | '/settings'
    | '/whatsapp'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/chat-embed/$companyId'
    | '/embed-form/$id'
    | '/f/$slug'
    | '/q/$slug'
    | '/analytics/tv'
    | '/integrations/meta'
    | '/leads/$id'
    | '/settings/automations'
    | '/settings/chat'
    | '/settings/company'
    | '/settings/install'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/quick-replies'
    | '/settings/routing'
    | '/settings/security'
    | '/settings/widgets'
    | '/api/public/meta-webhook'
    | '/api/public/pixel-event'
    | '/api/public/whatsapp-capi-retry'
    | '/api/public/whatsapp-click'
    | '/api/public/whatsapp-webhook'
    | '/functions/v1/oauth-callback'
    | '/integrations/meta/callback'
    | '/settings/'
    | '/quizzes/$id/builder'
    | '/quizzes/$id/flow'
    | '/quizzes/$id/leads'
    | '/quizzes/$id/performance'
    | '/quizzes/$id/preview'
    | '/quizzes/$id/publish'
    | '/api/public/cron/meta-retry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/google-oauth-callback'
    | '/meta-oauth-callback'
    | '/oauth-callback'
    | '/analytics'
    | '/automations'
    | '/chat-reports'
    | '/dashboard'
    | '/forms'
    | '/inbox'
    | '/leads'
    | '/observability'
    | '/pipeline'
    | '/quizzes'
    | '/whatsapp'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/chat-embed/$companyId'
    | '/embed-form/$id'
    | '/f/$slug'
    | '/q/$slug'
    | '/analytics/tv'
    | '/integrations/meta'
    | '/leads/$id'
    | '/settings/automations'
    | '/settings/chat'
    | '/settings/company'
    | '/settings/install'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/quick-replies'
    | '/settings/routing'
    | '/settings/security'
    | '/settings/widgets'
    | '/api/public/meta-webhook'
    | '/api/public/pixel-event'
    | '/api/public/whatsapp-capi-retry'
    | '/api/public/whatsapp-click'
    | '/api/public/whatsapp-webhook'
    | '/functions/v1/oauth-callback'
    | '/integrations/meta/callback'
    | '/settings'
    | '/quizzes/$id/builder'
    | '/quizzes/$id/flow'
    | '/quizzes/$id/leads'
    | '/quizzes/$id/performance'
    | '/quizzes/$id/preview'
    | '/quizzes/$id/publish'
    | '/api/public/cron/meta-retry'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/diagnostics'
    | '/google-oauth-callback'
    | '/meta-oauth-callback'
    | '/oauth-callback'
    | '/_app/analytics'
    | '/_app/automations'
    | '/_app/chat-reports'
    | '/_app/dashboard'
    | '/_app/forms'
    | '/_app/inbox'
    | '/_app/leads'
    | '/_app/observability'
    | '/_app/pipeline'
    | '/_app/quizzes'
    | '/_app/settings'
    | '/_app/whatsapp'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/chat-embed/$companyId'
    | '/embed-form/$id'
    | '/f/$slug'
    | '/q/$slug'
    | '/_app/analytics/tv'
    | '/_app/integrations/meta'
    | '/_app/leads/$id'
    | '/_app/settings/automations'
    | '/_app/settings/chat'
    | '/_app/settings/company'
    | '/_app/settings/install'
    | '/_app/settings/integrations'
    | '/_app/settings/notifications'
    | '/_app/settings/quick-replies'
    | '/_app/settings/routing'
    | '/_app/settings/security'
    | '/_app/settings/widgets'
    | '/api/public/meta-webhook'
    | '/api/public/pixel-event'
    | '/api/public/whatsapp-capi-retry'
    | '/api/public/whatsapp-click'
    | '/api/public/whatsapp-webhook'
    | '/functions/v1/oauth-callback'
    | '/integrations/meta/callback'
    | '/_app/settings/'
    | '/_app/quizzes_/$id/builder'
    | '/_app/quizzes_/$id/flow'
    | '/_app/quizzes_/$id/leads'
    | '/_app/quizzes_/$id/performance'
    | '/_app/quizzes_/$id/preview'
    | '/_app/quizzes_/$id/publish'
    | '/api/public/cron/meta-retry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DiagnosticsRoute: typeof DiagnosticsRoute
  GoogleOauthCallbackRoute: typeof GoogleOauthCallbackRoute
  MetaOauthCallbackRoute: typeof MetaOauthCallbackRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  ChatEmbedCompanyIdRoute: typeof ChatEmbedCompanyIdRoute
  EmbedFormIdRoute: typeof EmbedFormIdRoute
  FSlugRoute: typeof FSlugRoute
  QSlugRoute: typeof QSlugRoute
  ApiPublicMetaWebhookRoute: typeof ApiPublicMetaWebhookRoute
  ApiPublicPixelEventRoute: typeof ApiPublicPixelEventRoute
  ApiPublicWhatsappCapiRetryRoute: typeof ApiPublicWhatsappCapiRetryRoute
  ApiPublicWhatsappClickRoute: typeof ApiPublicWhatsappClickRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  FunctionsV1OauthCallbackRoute: typeof FunctionsV1OauthCallbackRoute
  IntegrationsMetaCallbackRoute: typeof IntegrationsMetaCallbackRoute
  ApiPublicCronMetaRetryRoute: typeof ApiPublicCronMetaRetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-oauth-callback': {
      id: '/google-oauth-callback'
      path: '/google-oauth-callback'
      fullPath: '/google-oauth-callback'
      preLoaderRoute: typeof GoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-oauth-callback': {
      id: '/meta-oauth-callback'
      path: '/meta-oauth-callback'
      fullPath: '/meta-oauth-callback'
      preLoaderRoute: typeof MetaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat-reports': {
      id: '/_app/chat-reports'
      path: '/chat-reports'
      fullPath: '/chat-reports'
      preLoaderRoute: typeof AppChatReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms': {
      id: '/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/observability': {
      id: '/_app/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof AppObservabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes': {
      id: '/_app/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/chat-embed/$companyId': {
      id: '/chat-embed/$companyId'
      path: '/chat-embed/$companyId'
      fullPath: '/chat-embed/$companyId'
      preLoaderRoute: typeof ChatEmbedCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed-form/$id': {
      id: '/embed-form/$id'
      path: '/embed-form/$id'
      fullPath: '/embed-form/$id'
      preLoaderRoute: typeof EmbedFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$slug': {
      id: '/q/$slug'
      path: '/q/$slug'
      fullPath: '/q/$slug'
      preLoaderRoute: typeof QSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytics/tv': {
      id: '/_app/analytics/tv'
      path: '/tv'
      fullPath: '/analytics/tv'
      preLoaderRoute: typeof AppAnalyticsTvRouteImport
      parentRoute: typeof AppAnalyticsRoute
    }
    '/_app/integrations/meta': {
      id: '/_app/integrations/meta'
      path: '/integrations/meta'
      fullPath: '/integrations/meta'
      preLoaderRoute: typeof AppIntegrationsMetaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$id': {
      id: '/_app/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AppLeadsIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/automations': {
      id: '/_app/settings/automations'
      path: '/automations'
      fullPath: '/settings/automations'
      preLoaderRoute: typeof AppSettingsAutomationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/chat': {
      id: '/_app/settings/chat'
      path: '/chat'
      fullPath: '/settings/chat'
      preLoaderRoute: typeof AppSettingsChatRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/install': {
      id: '/_app/settings/install'
      path: '/install'
      fullPath: '/settings/install'
      preLoaderRoute: typeof AppSettingsInstallRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/quick-replies': {
      id: '/_app/settings/quick-replies'
      path: '/quick-replies'
      fullPath: '/settings/quick-replies'
      preLoaderRoute: typeof AppSettingsQuickRepliesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/routing': {
      id: '/_app/settings/routing'
      path: '/routing'
      fullPath: '/settings/routing'
      preLoaderRoute: typeof AppSettingsRoutingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/widgets': {
      id: '/_app/settings/widgets'
      path: '/widgets'
      fullPath: '/settings/widgets'
      preLoaderRoute: typeof AppSettingsWidgetsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/public/meta-webhook': {
      id: '/api/public/meta-webhook'
      path: '/api/public/meta-webhook'
      fullPath: '/api/public/meta-webhook'
      preLoaderRoute: typeof ApiPublicMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pixel-event': {
      id: '/api/public/pixel-event'
      path: '/api/public/pixel-event'
      fullPath: '/api/public/pixel-event'
      preLoaderRoute: typeof ApiPublicPixelEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-capi-retry': {
      id: '/api/public/whatsapp-capi-retry'
      path: '/api/public/whatsapp-capi-retry'
      fullPath: '/api/public/whatsapp-capi-retry'
      preLoaderRoute: typeof ApiPublicWhatsappCapiRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-click': {
      id: '/api/public/whatsapp-click'
      path: '/api/public/whatsapp-click'
      fullPath: '/api/public/whatsapp-click'
      preLoaderRoute: typeof ApiPublicWhatsappClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/oauth-callback': {
      id: '/functions/v1/oauth-callback'
      path: '/functions/v1/oauth-callback'
      fullPath: '/functions/v1/oauth-callback'
      preLoaderRoute: typeof FunctionsV1OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/meta/callback': {
      id: '/integrations/meta/callback'
      path: '/integrations/meta/callback'
      fullPath: '/integrations/meta/callback'
      preLoaderRoute: typeof IntegrationsMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/quizzes_/$id/builder': {
      id: '/_app/quizzes_/$id/builder'
      path: '/quizzes/$id/builder'
      fullPath: '/quizzes/$id/builder'
      preLoaderRoute: typeof AppQuizzesIdBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes_/$id/flow': {
      id: '/_app/quizzes_/$id/flow'
      path: '/quizzes/$id/flow'
      fullPath: '/quizzes/$id/flow'
      preLoaderRoute: typeof AppQuizzesIdFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes_/$id/leads': {
      id: '/_app/quizzes_/$id/leads'
      path: '/quizzes/$id/leads'
      fullPath: '/quizzes/$id/leads'
      preLoaderRoute: typeof AppQuizzesIdLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes_/$id/performance': {
      id: '/_app/quizzes_/$id/performance'
      path: '/quizzes/$id/performance'
      fullPath: '/quizzes/$id/performance'
      preLoaderRoute: typeof AppQuizzesIdPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes_/$id/preview': {
      id: '/_app/quizzes_/$id/preview'
      path: '/quizzes/$id/preview'
      fullPath: '/quizzes/$id/preview'
      preLoaderRoute: typeof AppQuizzesIdPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes_/$id/publish': {
      id: '/_app/quizzes_/$id/publish'
      path: '/quizzes/$id/publish'
      fullPath: '/quizzes/$id/publish'
      preLoaderRoute: typeof AppQuizzesIdPublishRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/cron/meta-retry': {
      id: '/api/public/cron/meta-retry'
      path: '/api/public/cron/meta-retry'
      fullPath: '/api/public/cron/meta-retry'
      preLoaderRoute: typeof ApiPublicCronMetaRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAnalyticsRouteChildren {
  AppAnalyticsTvRoute: typeof AppAnalyticsTvRoute
}

const AppAnalyticsRouteChildren: AppAnalyticsRouteChildren = {
  AppAnalyticsTvRoute: AppAnalyticsTvRoute,
}

const AppAnalyticsRouteWithChildren = AppAnalyticsRoute._addFileChildren(
  AppAnalyticsRouteChildren,
)

interface AppLeadsRouteChildren {
  AppLeadsIdRoute: typeof AppLeadsIdRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsIdRoute: AppLeadsIdRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAutomationsRoute: typeof AppSettingsAutomationsRoute
  AppSettingsChatRoute: typeof AppSettingsChatRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsInstallRoute: typeof AppSettingsInstallRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsQuickRepliesRoute: typeof AppSettingsQuickRepliesRoute
  AppSettingsRoutingRoute: typeof AppSettingsRoutingRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsWidgetsRoute: typeof AppSettingsWidgetsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAutomationsRoute: AppSettingsAutomationsRoute,
  AppSettingsChatRoute: AppSettingsChatRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsInstallRoute: AppSettingsInstallRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsQuickRepliesRoute: AppSettingsQuickRepliesRoute,
  AppSettingsRoutingRoute: AppSettingsRoutingRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsWidgetsRoute: AppSettingsWidgetsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRouteWithChildren
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppChatReportsRoute: typeof AppChatReportsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFormsRoute: typeof AppFormsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppObservabilityRoute: typeof AppObservabilityRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppQuizzesRoute: typeof AppQuizzesRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIntegrationsMetaRoute: typeof AppIntegrationsMetaRoute
  AppQuizzesIdBuilderRoute: typeof AppQuizzesIdBuilderRoute
  AppQuizzesIdFlowRoute: typeof AppQuizzesIdFlowRoute
  AppQuizzesIdLeadsRoute: typeof AppQuizzesIdLeadsRoute
  AppQuizzesIdPerformanceRoute: typeof AppQuizzesIdPerformanceRoute
  AppQuizzesIdPreviewRoute: typeof AppQuizzesIdPreviewRoute
  AppQuizzesIdPublishRoute: typeof AppQuizzesIdPublishRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRouteWithChildren,
  AppAutomationsRoute: AppAutomationsRoute,
  AppChatReportsRoute: AppChatReportsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFormsRoute: AppFormsRoute,
  AppInboxRoute: AppInboxRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppObservabilityRoute: AppObservabilityRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppQuizzesRoute: AppQuizzesRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIntegrationsMetaRoute: AppIntegrationsMetaRoute,
  AppQuizzesIdBuilderRoute: AppQuizzesIdBuilderRoute,
  AppQuizzesIdFlowRoute: AppQuizzesIdFlowRoute,
  AppQuizzesIdLeadsRoute: AppQuizzesIdLeadsRoute,
  AppQuizzesIdPerformanceRoute: AppQuizzesIdPerformanceRoute,
  AppQuizzesIdPreviewRoute: AppQuizzesIdPreviewRoute,
  AppQuizzesIdPublishRoute: AppQuizzesIdPublishRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DiagnosticsRoute: DiagnosticsRoute,
  GoogleOauthCallbackRoute: GoogleOauthCallbackRoute,
  MetaOauthCallbackRoute: MetaOauthCallbackRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  ChatEmbedCompanyIdRoute: ChatEmbedCompanyIdRoute,
  EmbedFormIdRoute: EmbedFormIdRoute,
  FSlugRoute: FSlugRoute,
  QSlugRoute: QSlugRoute,
  ApiPublicMetaWebhookRoute: ApiPublicMetaWebhookRoute,
  ApiPublicPixelEventRoute: ApiPublicPixelEventRoute,
  ApiPublicWhatsappCapiRetryRoute: ApiPublicWhatsappCapiRetryRoute,
  ApiPublicWhatsappClickRoute: ApiPublicWhatsappClickRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  FunctionsV1OauthCallbackRoute: FunctionsV1OauthCallbackRoute,
  IntegrationsMetaCallbackRoute: IntegrationsMetaCallbackRoute,
  ApiPublicCronMetaRetryRoute: ApiPublicCronMetaRetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
